"""Reading benchmark instances from disk, and discovering the benchmark suite."""
from pathlib import Path

from .models import Item, Problem

MAX_N_CORRELATED = 1000
INCLUDE_GENERATED = True  # Include generated benchmarks (benchmarks/generated/)


def parse_benchmark_file(filepath):
    """Parses a benchmark .txt file.

    Standard format (.txt):
    - Line 1: n capacity (space-separated)
    - Following lines: value weight (profit then weight)
    """
    try:
        with open(filepath, 'r') as f:
            lines = [line.strip() for line in f.readlines()]

        first_line_parts = lines[0].split()
        n = int(first_line_parts[0])
        capacity = int(first_line_parts[1])

        items = []
        for i in range(n):
            parts = lines[1 + i].split()
            value = int(parts[0])
            weight = int(parts[1])
            items.append(Item(i, weight, value))

        return Problem(items, capacity)
    except Exception as e:
        print(f"Parsing error {filepath}: {e}")
        return None


def discover_benchmarks(base_path='benchmarks', max_n_correlated=None):
    """Automatically discovers all available benchmark files.

    Includes: low_dimension, large_scale, generated

    Args:
        base_path: Path to benchmarks folder
        max_n_correlated: Max size for correlated benchmarks (None = uses MAX_N_CORRELATED)

    Returns:
        dict: Structure containing benchmarks organized by category
    """
    if max_n_correlated is None:
        max_n_correlated = MAX_N_CORRELATED

    base = Path(base_path)

    if not base.exists():
        print(f"Folder '{base_path}' not found")
        return None

    structure = {
        'base_path': str(base),
        'benchmarks': {},
    }

    # Scan low_dimension and large_scale - WITHOUT size limit
    simple_categories = ['low_dimension', 'large_scale']

    for category in simple_categories:
        category_path = base / category
        if not category_path.exists():
            continue

        for file_path in category_path.glob('*.txt'):
            filename = file_path.name

            if category == 'low_dimension':
                parts = filename.replace('.txt', '').split('_')
                try:
                    n = int(parts[3])
                    cap = int(parts[4])
                except (IndexError, ValueError):
                    continue
            else:
                parts = filename.replace('.txt', '').split('_')
                try:
                    n = int(parts[2])
                    cap = int(parts[3])
                except (IndexError, ValueError):
                    continue

            # NO size filter for large_scale and low_dimension
            key = f"{category}_{filename}"
            structure['benchmarks'][key] = {
                'path': str(file_path),
                'correlation': category,
                'size': f"n={n}",
                'capacity': f"c={cap}",
                'n': n,
                'capacity_value': cap,
                'format': 'standard',
            }

    # Scan generated/ - .txt files generated by generate_benchmarks()
    if INCLUDE_GENERATED:
        generated_path = base / 'generated'
        if generated_path.exists():
            for file_path in generated_path.glob('*.txt'):
                filename = file_path.name
                # Format: {correlation}_n{n}_c{capacity}.txt or {correlation}_n{n}_c{capacity}_{index}.txt
                parts = filename.replace('.txt', '').split('_')
                try:
                    correlation = parts[0]
                    n = None
                    cap = None
                    for part in parts:
                        if part.startswith('n') and part[1:].isdigit():
                            n = int(part[1:])
                        elif part.startswith('c') and part[1:].isdigit():
                            cap = int(part[1:])

                    if n is None or cap is None:
                        continue

                    key = f"generated_{filename}"
                    structure['benchmarks'][key] = {
                        'path': str(file_path),
                        'correlation': f"generated_{correlation}",
                        'size': f"n={n}",
                        'capacity': f"c={cap}",
                        'n': n,
                        'capacity_value': cap,
                        'format': 'standard',
                    }
                except (IndexError, ValueError):
                    continue

    print(f"Discovered {len(structure['benchmarks'])} benchmarks")
    return structure
